### ISSUE TITLE
uTox crashing on Sway

### ISSUE THREAD

**Issue by sudo97** [uTox/uTox#1162]
Hi, I am using sway-wm which is wayland-based. When I try to check my web-cam it crashes.

**Comment by endoffile78** [comment]
What version of uTox are you using?

**Comment by sudo97** [comment]
It is 0.16.1, by the way on i3wm(which is xorg based) it also crashes

**Comment by endoffile78** [comment]
Ok, this might have been fixed by #1130 which is not in any of the released versions currently. It will be in the next one. You can compile uTox if you want. If you need help there is documentation [here](https://github.com/uTox/uTox/blob/develop/docs/BUILD.md#linux). I can also help you compile it too.

**Comment by savchenko** [comment]
FWIW, still crashes on Sway v1.5  
uTox version 0.18.0-1, from [Debian Bullseye](https://packages.debian.org/bullseye/utox) (currently "testing").
