### ISSUE TITLE
Tray icon only visible as white vertical bar

### ISSUE THREAD

**Issue by Quix0r** [uTox/uTox#185]
The tray icon is only visible as white vertical bar and barely clickable (to open the main window). Sadly the file upload is not working here. :-(

My System is Debian Jessie and FVWM-Crystal 3.3.1 as window manager. Other applications, e.g. peerunity just shows up normal.
##

**Comment by ingvar1995** [comment]
linux?

**Comment by Quix0r** [comment]
Yes, sorry not to mention it. I have Debian Linux and GCC 5.3.1

**Comment by ingvar1995** [comment]
I have same problem but in my case icon is clickable and tox logo appears after first click.

**Comment by GrayHatter** [comment]
What's your desktop window manager?

**Comment by Quix0r** [comment]
FVWM-Crystal.

**Comment by GrayHatter** [comment]
what version are you using?

**Comment by Quix0r** [comment]
Updated again, Debian Jessie is 8.0 I guess.

**Comment by GrayHatter** [comment]
Version of uTox?

**Comment by Quix0r** [comment]
I use master.

**Comment by GrayHatter** [comment]
what version is in your title bar?

**Comment by strk** [comment]
Same happens to me with 2a1a7ce56e1845a7346c8d3e8e3088d2d4e605fd on an Ubuntu 14.04.4 with Gnome metacity. Tox titlebar version is v0.6.1-18-g2a1a7cea

**Comment by strk** [comment]
See also https://github.com/tux3/qTox/issues/1067 which reported the same problem with qTox, and should have pointers to QT bugs IIRC.

**Comment by strk** [comment]
Debugging output, if enabled, report:
```
Tray size == 32 x 32
Tray size == 1 x 24
```

As if the tray manager refuses to accept the size utox code wants to give to the icon window.
Same happens when trying with a icon size of 24x24 or 16x16

**Comment by GrayHatter** [comment]
after a little more investigation, I'm going to file this under upstream... The tray embeds correctly in other trays, gnome seems to be the only one broken.

**Comment by strk** [comment]
This seems to be how qt fixed it:
http://code.qt.io/cgit/qt/qtbase.git/commit/?h=5.4&id=612953a626ec21b8518ee23a4f5268b566cf41e5

If I read the code correctly they wait for an XEMBED_EMBEDDED_NOTIFY event and then map the icon window

**Comment by Quix0r** [comment]
With latest master (and toxcore, of course), no change. Only to report it. :)

**Comment by GrayHatter** [comment]
https://github.com/GrayHatter/uTox/tree/tray_fixes if you know gdb break on src/xlib/main.c:575 and print event

**Comment by strk** [comment]
```
(gdb) print event
$1 = {type = 33, xany = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, window = 54526156}, xkey = {type = 33, serial = 1036,
    send_event = 1, display = 0xd26090, window = 54526156, root = 403, subwindow = 67749235033899040, time = 0, x = 0, y = 0, x_root = 0,
    y_root = 0, state = 21006048, keycode = 0, same_screen = -1}, xbutton = {type = 33, serial = 1036, send_event = 1, display = 0xd26090,
    window = 54526156, root = 403, subwindow = 67749235033899040, time = 0, x = 0, y = 0, x_root = 0, y_root = 0, state = 21006048, button = 0,
    same_screen = -1}, xmotion = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, window = 54526156, root = 403,
    subwindow = 67749235033899040, time = 0, x = 0, y = 0, x_root = 0, y_root = 0, state = 21006048, is_hint = 0 '\000', same_screen = -1},
  xcrossing = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, window = 54526156, root = 403, subwindow = 67749235033899040,
    time = 0, x = 0, y = 0, x_root = 0, y_root = 0, mode = 21006048, detail = 0, same_screen = -1, focus = -1, state = 5843993}, xfocus = {
    type = 33, serial = 1036, send_event = 1, display = 0xd26090, window = 54526156, mode = 403, detail = 0}, xexpose = {type = 33, 
    serial = 1036, send_event = 1, display = 0xd26090, window = 54526156, x = 403, y = 0, width = 32, height = 15774098, count = 0}, 
  xgraphicsexpose = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, drawable = 54526156, x = 403, y = 0, width = 32, 
    height = 15774098, count = 0, major_code = 0, minor_code = 0}, xnoexpose = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, 
    drawable = 54526156, major_code = 403, minor_code = 0}, xvisibility = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, 
    window = 54526156, state = 403}, xcreatewindow = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, parent = 54526156, 
    window = 403, x = 32, y = 15774098, width = 0, height = 0, border_width = 0, override_redirect = 0}, xdestroywindow = {type = 33, 
    serial = 1036, send_event = 1, display = 0xd26090, event = 54526156, window = 403}, xunmap = {type = 33, serial = 1036, send_event = 1, 
    display = 0xd26090, event = 54526156, window = 403, from_configure = 32}, xmap = {type = 33, serial = 1036, send_event = 1, 
    display = 0xd26090, event = 54526156, window = 403, override_redirect = 32}, xmaprequest = {type = 33, serial = 1036, send_event = 1, 
    display = 0xd26090, parent = 54526156, window = 403}, xreparent = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, 
    event = 54526156, window = 403, parent = 67749235033899040, x = 0, y = 0, override_redirect = 0}, xconfigure = {type = 33, serial = 1036, 
    send_event = 1, display = 0xd26090, event = 54526156, window = 403, x = 32, y = 15774098, width = 0, height = 0, border_width = 0, above = 0, 
    override_redirect = 21006048}, xgravity = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, event = 54526156, window = 403, 
    x = 32, y = 15774098}, xresizerequest = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, window = 54526156, width = 403, 
    height = 0}, xconfigurerequest = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, parent = 54526156, window = 403, x = 32, 
    y = 15774098, width = 0, height = 0, border_width = 0, above = 0, detail = 21006048, value_mask = 18446744073709551615}, xcirculate = {
    type = 33, serial = 1036, send_event = 1, display = 0xd26090, event = 54526156, window = 403, place = 32}, xcirculaterequest = {type = 33, 
    serial = 1036, send_event = 1, display = 0xd26090, parent = 54526156, window = 403, place = 32}, xproperty = {type = 33, serial = 1036, 
    send_event = 1, display = 0xd26090, window = 54526156, atom = 403, time = 67749235033899040, state = 0}, xselectionclear = {type = 33, 
    serial = 1036, send_event = 1, display = 0xd26090, window = 54526156, selection = 403, time = 67749235033899040}, xselectionrequest = {
    type = 33, serial = 1036, send_event = 1, display = 0xd26090, owner = 54526156, requestor = 403, selection = 67749235033899040, target = 0, 
    property = 0, time = 0}, xselection = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, requestor = 54526156, selection = 403, 
    target = 67749235033899040, property = 0, time = 0}, xcolormap = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, 
    window = 54526156, colormap = 403, new = 32, state = 15774098}, xclient = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, 
    window = 54526156, message_type = 403, format = 32, data = {b = '\000' <repeats 19 times>, s = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, l = {0, 0, 0, 
        21006048, -1}}}, xmapping = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, window = 54526156, request = 403, 
    first_keycode = 0, count = 32}, xerror = {type = 33, display = 0x40c, resourceid = 1, serial = 13787280, error_code = 204 '\314', 
    request_code = 0 '\000', minor_code = 64 '@'}, xkeymap = {type = 33, serial = 1036, send_event = 1, display = 0xd26090, window = 54526156,
    key_vector = "\223\001\000\000\000\000\000\000 \000\000\000\222\261\360", '\000' <repeats 16 times>}, xgeneric = {type = 33, serial = 1036,
    send_event = 1, display = 0xd26090, extension = 54526156, evtype = 0}, xcookie = {type = 33, serial = 1036, send_event = 1,
    display = 0xd26090, extension = 54526156, evtype = 0, cookie = 403, data = 0xf0b19200000020}, pad = {140733193388065, 1036, 1, 13787280,
    54526156, 403, 67749235033899040, 0, 0, 0, 21006048, -1, 30190596439747609, 20304754251086891, 30190587848630542, 51944726058796656,
    39513484384626771, 29351703428283949, 24273020564685881, 11288767489383187, 11288776079317781, 11006197295946260, 11288776079251988,
    10160668559022355}}
(gdb)           
```

**Comment by strk** [comment]
The problem also occurs with MATE Panel 1.8.1 (Debian 8.2 / Mate desktop)

**Comment by strk** [comment]
I think the mate panel docker is `Notification Area 1.8.1`

**Comment by pizzamaker** [comment]
FIY, still happening on GNOME 3.20

**Comment by Getron** [comment]
Same problem here, uTox icon is only bad to recognize on a dark theme.

My OS is Netrunner 2016.01 KDE Arch Rolling release with QtCurve and dark arc and dark kde breeze system theme.

**Comment by stormchaser3000** [comment]
there is no system tray icon for me on xfce on arch linux

**Comment by GrayHatter** [comment]
pushed to https://github.com/uTox/uTox/tree/tray_fixes branch, please test and tell me if this fixes this issue

If not, run uTox with `-vvvv` and give me the output (May include private data, so redact as you deem necessary, or find me on irc http://webchat.freenode.net/?channels=#utox

**Comment by strk** [comment]
The bug is still there on a Debian 8 system with Mate desktop
as of c38ef6ca687de130e1ef69199a25b717d6521208 

With the same commit, -vvvv exists immediately after showing the version
(uTox version: 0.6.1)

**Comment by strk** [comment]
Sorry, I just realized I was in the wrong branch (from your fork).
Now switched to 4f6b77fff274ecad0d0c5c8268a65b964c111746 from utox/utox
but will take time for me to build it because it requires cmake 3.2 while
Debian 8 has 3.0.2. Are you really sure 3.0 can't work ?

**Comment by GrayHatter** [comment]
I have no idea what cmake version is really required, 3.2 is what i was
told to use when writing the cmake, and  Arch  doesn't use old packages.

And all of our Debian developers use the sid repos.

**Comment by strk** [comment]
3.0 seems to work, although I still didn't complete a build successfully
(missing libv4l headers...) - would you accept a PR to downgrade dependency
(or could you just push that yourself?)

**Comment by strk** [comment]
Ok this I don't know if can be related to cmake version:
```
/usr/src/tox/uTox/src/av/audio.c:487:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (uint64_t index = 0; index < buf_size; ++index) {
     ^
```

Missing -std flag ?

**Comment by strk** [comment]
So anyway, I built on a different machine, with cmake-3.5 and
gcc 5.4.0 (after building toxcore 0.1 from toktok branch) and
the bug is still there as of commit 4f6b77fff274ecad0d0c5c8268a65b964c111746

I still get a white vertical bar as the tray icon.

Log of stdout and stderr on -vvvv: http://strk.kbt.io/tmp/utox.log

**Comment by GrayHatter** [comment]
I pushed a new commit that I hope will fix the issue for you

**Comment by strk** [comment]
Still no dices with 51cec28491cb6717df336382691d3773767ae563
See http://strk.kbt.io/tmp/utox2.log

**Comment by GrayHatter** [comment]
@strk apply this patch, then gist the log pls
[patch.txt](https://github.com/uTox/uTox/files/891381/patch.txt)

```diff
diff --git a/src/xlib/tray.c b/src/xlib/tray.c
index fa097138..1d3ce78d 100644
--- a/src/xlib/tray.c
+++ b/src/xlib/tray.c
@@ -131,10 +131,7 @@ void create_tray_icon(void) {
                                              BlackPixel(display, def_screen_num),
                                              WhitePixel(display, def_screen_num));
 
-    XSelectInput(display, tray_window.window,
-                    ExposureMask        | ButtonPressMask | ButtonReleaseMask |
-                    EnterWindowMask     | LeaveWindowMask |
-                    StructureNotifyMask | FocusChangeMask | PropertyChangeMask);
+    XSelectInput(display, tray_window.window, ~0);
 
     /* Get ready to draw a tray icon */
     tray_window.gc        = XCreateGC(display, root_window, 0, 0);
```

**Comment by GrayHatter** [comment]
My current though is that gnome is being stupid... and tries to use the windows HINTs to get the tray icon. Instead of using the actual window.

see also https://github.com/GNOME/gdm/commit/8dcb33ffc74ebe16e467dcdf53e7beece06f37e8#diff-f3077a624c0d3068cf2de76b0ee94de0R355 cause it makes me think this is part of the problem.

maybe someone from @GNOME

**Comment by strk** [comment]
Same behavior with that patch.

**Comment by strk** [comment]
And log:
http://strk.kbt.io/tmp/utox3.log

**Comment by Quix0r** [comment]
OT: I'm now at work but at home I try to rewrite toxcore detection as a cmake module.

**Comment by GrayHatter** [comment]
@strk I just pushed 4038620c to tray_fixes with another patch I hope will work

**Comment by GrayHatter** [comment]
if it still fails, try changing lines 42,43 from `64u` to `24u`

Or reply here or irc and I'll push a patch.

**Comment by strk** [comment]
As I just changed machine, I want to report that
51cec28491cb6717df336382691d3773767ae563 works fine
on a "GNOME Flashback" desktop with Lubuntu.

It still fails (as I was reporting) when running against a remote
display with Mate desktop running (on Debian 8).

Will now try latest changes with both setup

**Comment by strk** [comment]
With 4038620cc66325a2668c89e0dfcd4735152796c8 the icon
on the GNOME Flashback panel is wider than it was with
the previously reported success (too wide).

And it works *GREAT* when rendering on the remote desktop!
Kudos !

Now... can you see a reason for that icon to be double width
on the local one ? Actually replacing 64u with 24u looks
great on both setups (except non-transparent background but
that's a style issue, completely different form this one)

**Comment by GrayHatter** [comment]
if you can try 32x32, I'll make that the default

**Comment by GrayHatter** [comment]
it's probably too wide because I'm setting the min_width/hight to 64x64 instead of something more reasonable like 16x16, and then flashback is being sane and following my directions, whereas default Gnome thinks it knows better

**Comment by strk** [comment]
This is too wide on GNOME Flashback:
```
    ._.w = 32u,
    ._.h = 32u,
```

See http://strk.kbt.io/tmp/tray_tox_gnome_32x32.png

Isn't the icon square ?

This is fine:
```
    ._.w = 24u,
    ._.h = 32u,
```

Here's what you see on Mate panel (big icons):
http://strk.kbt.io/tmp/tray_tox.png

Here's on GNOME Flashback (small icons):
http://strk.kbt.io/tmp/tray_tox_gnome.png

**Comment by GrayHatter** [comment]
Ahh, cool, I understand.

We should set the minimum size to 24, the default to 128, then resize to
the smaller of the square, so probably 84x84, and 24x24 respectively

**Comment by GrayHatter** [comment]
Thanks for all your help debugging this!!

It's nice to get this one finally solved!

**Comment by strk** [comment]
Thank you for fixing it !

**Comment by GrayHatter** [comment]
I just pushed another fix which should set sane defaults on both systems.

If it doesn't stay a square, let me know

**Comment by strk** [comment]
Icon is square on both displays with
commit 2a55f158ec8235e6425a656d78021e4694f9f79f

**Comment by Quix0r** [comment]
Totally OT: Rewrite pushed, but `filter_audio.h` cannot be found. I use this toxcore: git://github.com/TokTok/c-toxcore.git

**Comment by GrayHatter** [comment]
this is already merged into staging, and will be in develop soon
