### ISSUE TITLE
Chat history not saved

### ISSUE THREAD

**Issue by Tamarindo94** [uTox/uTox#779]
Even though I have the "Save chat history" option enabled, chat contents are deleted each time I close the program

**Comment by redmanmale** [comment]
What version you are using?
It was fixed some time ago.

Possible duplicate of #770.

**Comment by robinlinden** [comment]
This was an issue on Windows uTox between 0.12.0 and 0.12.2. It's fixed in 0.13.0. Please try the latest version and let us know if that solves it for you. 

The problem was that chatlogs were accidentally getting set to read-only, so the issue didn't cause any loss of existing data.

**Comment by redmanmale** [comment]
I checked it on 0.13.0 it was fixed.

**Comment by Tamarindo94** [comment]
I can confirm it is version 0.13.0, 64-bit, on Windows. I just tested it and the problem is still there

**Comment by robinlinden** [comment]
Can you run uTox from the cmdline like so: `utox.exe -vvvv > utox_log.txt` and see if there's anything relevant in there? Please note that this log **will contain your and contacts' Tox IDs** unless you go through and delete them.

Do you have any utf8 characters in your Windows username?

`-vvvv` specifies the verbosity of our logging. `> utox_log.txt` redirects all output from the cmdline to that text file. You might also want to try running `utox.exe -p` (portable mode) to see if this happens on a clean profile in a different location too.

You can also join [#uTox on Freenode](https://webchat.freenode.net/?channels=utox) and see if we can work out why this fix isn't working for you.

**Comment by Tamarindo94** [comment]
The log file has this line:

Chatlog:      Can't malloc that much, you'll probably have to move or delete your history for this peer.
		Friend number [...], count 2, actual_count 1, start at 0, error size 1931502957.

Is it relevant?

**Comment by GrayHatter** [comment]
yes, your logfile is corrupted

if you need the data, don't delete it. But if you don't need past history, and only need future conversations to save. You can delete that file and anything said it the future will be saved.

**Comment by Tamarindo94** [comment]
The fact is, that logfile was created after I launched uTox with the command suggested by robinlinden. I noticed that I have a file in AppData\Roaming with the name "[Contact's ID].new.txt" which contains the history in plain text, nonetheless the chat window is empty each time I launch uTox

**Comment by GrayHatter** [comment]
Can you grab the latest version v0.14 and check if this is still an issue. @robinlinden changed some related things so he may be able to say where this issue is coming from.

**Comment by robinlinden** [comment]
No idea. As far as I know, the only things that should corrupt our chatlogs is a crash or similar during a write.

We might want to do something like:
read chatlog from disk as we do now
if corrupt -> create tmp
read line from chatlog and write it to tmp
repeat ^ until we encounter a corrupt line
mv chatlog -> chatlog.broken; mv tmp -> chatlog

Would allow us to recover all but the corrupt data and minimally disrupt the user if something is broken.

**Comment by robinlinden** [comment]
@Tamarindo94 Even if the chatlog doesn't look corrupt, it likely is. It's not 100% plaintext. uTox uses a lot of control characters to know e.g. if the message was received by the other party or how long the author's name is. If all text looks okay, some of the metadata is probably missing.

**Comment by GrayHatter** [comment]
@robinlinden if you wanna be fancy you can seek out/back by `\n` and try to read/guess length

Then set sane defaults, and you're likely to be able to recover most if not the messages.

At the very least, using `\n` as message deliminators you'd be able to detect and ignore the bad blocks.

**Comment by redmanmale** [comment]
Reproduced on v.0.14.0 (Win x86).
Log:
```
Tox Callbacks: Friend	0	--	Standard Message: foo
uTox Audio:   Going to start notification tone!
uTox Audio:   close device set!
Toxcore:      Sent typing state to friend (0): 1
Toxcore:      Sending message, receipt 1
Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 0 receipt_number 4 
```

**Comment by GrayHatter** [comment]
This I now think is a toxcore bug... 

https://github.com/TokTok/c-toxcore/pull/500

will have to investigate deeper

**Comment by redmanmale** [comment]
It's reproduced almost each time on the fresh profile on Ubuntu with the same log.

**Comment by redmanmale** [comment]
Still here.

**Comment by redmanmale** [comment]
I tried really hard to reproduce this on all of available systems (Win 7, Win 8.1, Ubuntu 16.04 x2, 17.04) and failed. I don't know what had happened when I tested it last time but now it works just like it should.

So if any of you encountered it again let's reopen but for now I'm going to close this.

**Comment by xloem** [comment]
for googlers, these logfiles are found in `~/.config/tox/` and `./tox/`
